### PR TITLE
Adding 'strip workspace path' and workaround for Mercurial plugin incompatibility

### PR DESCRIPTION
**Pull request by mwhitecoverity**

### CODE REVIEW

**Comment by jbriggs22** [comment]
This was fixed in 1.9.0 with the Default behaviour for adding strip path is workspace when no strip paths are provided (see [CovAnalyzeCommand.java)](https://github.com/jenkinsci/coverity-plugin/blob/master/src/main/java/jenkins/plugins/coverity/CoverityTool/CovAnalyzeCommand.java)

**Comment by mwhitecoverity** [comment]
@jbriggs22 Doesn't that part only execute if TA is called? The intention was to strip path for all kinds of analysis.

**Comment by jbriggs22** [comment]
@mwhitecoverity you are correct, I overlooked that since I was thinking it was related to TA because of the Mercurial issue (SCM information is only used for TA in the plugin). I realize now this is 2 different issues being fixed, we can try to include this in an upcoming release.

**Comment by jbriggs22** [comment]
@mwhitecoverity since there are conflicts I'm going to close this, also since work is mainly done on an internal Coverity release branch this wouldn't be merged here anyways. For the 2 issues this fixes I've filed 2 internal Coverity BZs (#112049 & #112050), however I realized the issue with Mercurial can now be avoided by adding a Coverity Build step. If you add a Coverity build step the launcher will not wrap anything in cov-build that is not the Coverity build step.

**Pull request closed without merging**
